version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-backend
    working_dir: /app/BE
    command: npm start
    ports:
      - "8001:8001"
    env_file:
      - BE/.env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: app
      DB_PASS: secret
      DB_NAME: streaming
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - .:/app:cached
      - /app/BE/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-frontend
    working_dir: /app/FE
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - /app/FE/node_modules

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: streaming
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data: